goldenrod_house1_MapScripts::
	.byte 0

goldenrod_house1_EventScript_TrainDreamer::
	msgbox goldenrod_house1_Text_TrainDreamer, MSGBOX_NPC
	end

goldenrod_house1_EventScript_TowerWatcher::
	msgbox goldenrod_house1_Text_TowerWatcher, MSGBOX_NPC
	end

goldenrod_house1_Text_TrainDreamer::
	.string "The train station makes\n"
	.string "people dream about far\l"
	.string "away cities.$"

goldenrod_house1_Text_TowerWatcher::
	.string "I came for shopping and\n"
	.string "spent an hour staring at\l"
	.string "the RADIO TOWER.$"
