goldenrod_house2_MapScripts::
	.byte 0

goldenrod_house2_EventScript_GymFan::
	msgbox goldenrod_house2_Text_GymFan, MSGBOX_NPC
	end

goldenrod_house2_EventScript_CoinCaseOwner::
	msgbox goldenrod_house2_Text_CoinCaseOwner, MSGBOX_NPC
	end

goldenrod_house2_Text_GymFan::
	.string "WHITNEY's fans argue about\n"
	.string "strategy like it is\l"
	.string "weather.$"

goldenrod_house2_Text_CoinCaseOwner::
	.string "I keep my COIN CASE away\n"
	.string "from my snack money.\p"
	.string "That rule has saved me\n"
	.string "more than once.$"
