azalea_kurts_house_MapScripts::
	.byte 0

azalea_kurts_house_EventScript_ApricornApprentice::
	msgbox azalea_kurts_house_Text_ApricornApprentice, MSGBOX_NPC
	end

azalea_kurts_house_EventScript_SlowpokeKid::
	msgbox azalea_kurts_house_Text_SlowpokeKid, MSGBOX_NPC
	end

azalea_kurts_house_Text_ApricornApprentice::
	.string "KURT can tell an APRICORN\n"
	.string "apart by sound.\p"
	.string "I still need to look\n"
	.string "twice.$"

azalea_kurts_house_Text_SlowpokeKid::
	.string "SLOWPOKE naps like it has\n"
	.string "never heard of deadlines.\p"
	.string "Maybe that is wisdom.$"
