VioletCity_MapScripts::
	.byte 0

VioletCity_EventScript_TownSign::
	msgbox VioletCity_Text_TownSign, MSGBOX_SIGN
	end

VioletCity_Text_TownSign::
	.string "VIOLET CITY\n"
	.string "The City of\n"
	.string "Nostalgic Scents$"

VioletCity_EventScript_PokeCenterSign::
	msgbox VioletCity_Text_PokeCenterSign, MSGBOX_SIGN
	end

VioletCity_Text_PokeCenterSign::
	.string "POKEMON CENTER$"

VioletCity_EventScript_MartSign::
	msgbox VioletCity_Text_MartSign, MSGBOX_SIGN
	end

VioletCity_Text_MartSign::
	.string "POKEMON MART$"

VioletCity_EventScript_SproutTowerSign::
	msgbox VioletCity_Text_SproutTowerSign, MSGBOX_SIGN
	end

VioletCity_Text_SproutTowerSign::
	.string "SPROUT TOWER\n"
	.string "Experience the Way\n"
	.string "of POKEMON$"
