GoldenrodCity_MapScripts::
	.byte 0

GoldenrodCity_EventScript_PokeCenterSign::
	msgbox GoldenrodCity_Text_PokeCenterSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_PokeCenterSign::
	.string "POKEMON CENTER$"

GoldenrodCity_EventScript_DeptStoreSign::
	msgbox GoldenrodCity_Text_DeptStoreSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_DeptStoreSign::
	.string "Full Selection of\n"
	.string "POKEMON Goods!\p"
	.string "GOLDENROD CITY\n"
	.string "DEPT. STORE$"

GoldenrodCity_EventScript_RadioTowerSign::
	msgbox GoldenrodCity_Text_RadioTowerSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_RadioTowerSign::
	.string "GOLDENROD RADIO TOWER$"

GoldenrodCity_EventScript_GameCornerSign::
	msgbox GoldenrodCity_Text_GameCornerSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_GameCornerSign::
	.string "Your Playground!\p"
	.string "GOLDENROD CITY\n"
	.string "GAME CORNER$"

GoldenrodCity_EventScript_BikeShopSign::
	msgbox GoldenrodCity_Text_BikeShopSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_BikeShopSign::
	.string "The World is a\n"
	.string "Cycle Path!\n"
	.string "BIKE SHOP$"

GoldenrodCity_EventScript_TrainStationSign::
	msgbox GoldenrodCity_Text_TrainStationSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_TrainStationSign::
	.string "GOLDENROD STATION$"

GoldenrodCity_EventScript_FlowerShopSign::
	msgbox GoldenrodCity_Text_FlowerShopSign, MSGBOX_SIGN
	end

GoldenrodCity_Text_FlowerShopSign::
	.string "Blooming Beautiful\n"
	.string "FLOWER SHOP$"
