EcruteakCity_MapScripts::
	.byte 0

EcruteakCity_EventScript_TownSign::
	msgbox EcruteakCity_Text_TownSign, MSGBOX_SIGN
	end

EcruteakCity_Text_TownSign::
	.string "ECRUTEAK CITY\n"
	.string "A Historical City\p"
	.string "Where the Past Meets\n"
	.string "the Present$"

EcruteakCity_EventScript_PokeCenterSign::
	msgbox EcruteakCity_Text_PokeCenterSign, MSGBOX_SIGN
	end

EcruteakCity_Text_PokeCenterSign::
	.string "POKEMON CENTER$"

EcruteakCity_EventScript_MartSign::
	msgbox EcruteakCity_Text_MartSign, MSGBOX_SIGN
	end

EcruteakCity_Text_MartSign::
	.string "POKEMON MART$"

EcruteakCity_EventScript_BurnedTowerSign::
	msgbox EcruteakCity_Text_BurnedTowerSign, MSGBOX_SIGN
	end

EcruteakCity_Text_BurnedTowerSign::
	.string "BURNED TOWER\p"
	.string "It was destroyed by a\n"
	.string "mysterious fire.\p"
	.string "Please stay away, as\n"
	.string "it is unsafe.$"

EcruteakCity_EventScript_TinTowerSign::
	msgbox EcruteakCity_Text_TinTowerSign, MSGBOX_SIGN
	end

EcruteakCity_Text_TinTowerSign::
	.string "TIN TOWER\p"
	.string "A legendary POKEMON is\n"
	.string "said to roost here.$"
