Route39_MapScripts::
	.byte 0

Route39_EventScript_RouteSign::
	msgbox Route39_Text_RouteSign, MSGBOX_SIGN
	end

Route39_Text_RouteSign::
	.string "ROUTE 39\n"
	.string "OLIVINE CITY -\n"
	.string "ECRUTEAK CITY$"

Route39_EventScript_MoomooFarmSign::
	msgbox Route39_Text_MoomooFarmSign, MSGBOX_SIGN
	end

Route39_Text_MoomooFarmSign::
	.string "MOOMOO FARM\n"
	.string "Enjoy Our Fresh and\n"
	.string "Tasty Milk$"
