violet_house1_MapScripts::
	.byte 0

violet_house1_EventScript_FisherMother::
	msgbox violet_house1_Text_FisherMother, MSGBOX_NPC
	end

violet_house1_EventScript_MapReader::
	msgbox violet_house1_Text_MapReader, MSGBOX_NPC
	end

violet_house1_Text_FisherMother::
	.string "My son says every pond has\n"
	.string "a secret.\p"
	.string "I say every secret still\n"
	.string "needs a good line.$"

violet_house1_Text_MapReader::
	.string "VIOLET sits between caves,\n"
	.string "towers, and long grass.\p"
	.string "No wonder travelers keep\n"
	.string "checking their maps.$"
