AzaleaTown_MapScripts::
	.byte 0

AzaleaTown_EventScript_TownSign::
	msgbox AzaleaTown_Text_TownSign, MSGBOX_SIGN
	end

AzaleaTown_Text_TownSign::
	.string "AZALEA TOWN\n"
	.string "Where People and POKEMON\n"
	.string "Live in Happy Harmony$"

AzaleaTown_EventScript_PokeCenterSign::
	msgbox AzaleaTown_Text_PokeCenterSign, MSGBOX_SIGN
	end

AzaleaTown_Text_PokeCenterSign::
	.string "POKEMON CENTER$"

AzaleaTown_EventScript_MartSign::
	msgbox AzaleaTown_Text_MartSign, MSGBOX_SIGN
	end

AzaleaTown_Text_MartSign::
	.string "POKEMON MART$"

AzaleaTown_EventScript_SlowpokeWellSign::
	msgbox AzaleaTown_Text_SlowpokeWellSign, MSGBOX_SIGN
	end

AzaleaTown_Text_SlowpokeWellSign::
	.string "SLOWPOKE WELL\p"
	.string "Also known as the\n"
	.string "RAINMAKER WELL.\p"
	.string "Locals believe that a\n"
	.string "SLOWPOKE's yawn summons rain.\p"
	.string "Records show that a\n"
	.string "SLOWPOKE's yawn ended a\n"
	.string "drought 400 years ago.$"
