Route38_MapScripts::
	.byte 0

Route38_EventScript_RouteSign::
	msgbox Route38_Text_RouteSign, MSGBOX_SIGN
	end

Route38_Text_RouteSign::
	.string "ROUTE 38\n"
	.string "OLIVINE CITY -\n"
	.string "ECRUTEAK CITY$"

Route38_EventScript_MoomooFarmSign::
	msgbox Route38_Text_MoomooFarmSign, MSGBOX_SIGN
	end

Route38_Text_MoomooFarmSign::
	.string "MOOMOO FARM\n"
	.string "Enjoy Our Fresh and\n"
	.string "Tasty Milk$"
